
version: "3.7"

services:
  workspace:
    image: bresnow/baseworkspace:latest
    environment:
      - WRK_HOST="192.168.50.189"
    deploy:
      placement:
        constraints:
          - node.labels.popos == true
      labels:
      # To create user:password pair, it's possible to use this command:
      # In any workspace-in-docker execute in terminal:  echo $(htpasswd -nB <userName>) | sed -e s/\\$/\\$\\$/g
      #   (csubstitute <userName> with the user name of your choice)
      #   and enter password (twice) 
      #   by default the user:pass is admin:admin
      # You can have multiple <user:pass> separated with "," 
      - "traefik.http.middlewares.basic-auth.basicauth.users=admin:$$2y$$05$$eub6CV.CwUYCCQjNBvSf5uZnzdRmVwGZ/ncxecb9O7WxCR8aLuM3K"
      - "traefik.enable=true"
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      # cronicle
      - "traefik.http.services.cronicle.loadbalancer.server.port=8023"
      - "traefik.http.routers.cronicle.service=cronicle"
      - "traefik.http.routers.cronicle.rule=PathPrefix(`/`)"
      - "traefik.http.routers.cronicle.entrypoints=cronicle"
      - "traefik.http.routers.cronicle.middlewares=basic-auth"
       # ide
      # - "traefik.http.services.terminal.loadbalancer.server.port=8026"
      # - "traefik.http.routers.terminal.service=ide"
      # - "traefik.http.routers.terminal.rule=PathPrefix(`/ide`)"
      # - "traefik.http.routers.terminal.entrypoints=ide"
      # - "traefik.http.routers.terminal.middlewares=basic-auth"    
    networks:
      - proxy
    volumes:
networks:
  proxy:
    external: true
    name: traefik-public